# -*- coding: utf-8 -*-
"""product review

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXAVy8AFWX0-2s8eBHgkaskRkn_nrrY1
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

sentences=reviews.split(".")
pros = []
cons = []
for s in sentences:
    s=s.strip()
    if s == "":
        continue
    result=sentiment(s)[0]
    if result["label"]=="POSITIVE":
        pros.append(s)
    elif result["label"]=="NEGATIVE":
        cons.append(s)
pros=pros[:2]
cons=cons[:2]
df=pd.DataFrame({
      "pros":pros,
      "cons":cons

})
df

sentiment = pipeline("sentiment-analysis")
reviews="""the laptop starts quickly and works smoothly for daily tasks.
the screen quality is clear and good for watching videos.
battery backup is average and needs charging often."""