# -*- coding: utf-8 -*-
"""text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAFZOr7xtQuFzo_Vpff0dk38hBuDPIA_
"""

!pip install transformers torch

from transformers import pipeline
generator = pipeline(
    "text-generation",
    model="gpt2"
)
prompt="artrificial intelligence in finance will"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI generated text:")
print(result[0]['generated_text'])